### PR TITLE
Upgrade centos

### PR DESCRIPTION
**Pull request by erikh**
This upgrades the centos box and pushes 0.8.0. I didn't wait for the PR to arrive because I wanted to be sure the box would build.

I have eliminated vmware; I don't use it and I don't think @unclejack does either, so there's no point.

The sshd fix @shaleman found has also been applied.

/cc @mapuri

### CODE REVIEW

**Comment by mapuri** [comment]
LGTM. thanks @erikh 

I think @shaleman had hit the PAM issue for Ubuntu vms though, so we may need to fix Ubuntu boxes too?

**Comment by erikh** [comment]
Oh. can someone else take care of that? I'm not familiar with those boxes anymore.

**Comment by mapuri** [comment]
ping @shaleman , he added the Ubuntu boxes iirc

Shall we revert the centos related change then, as I think centos was working fine for him?

Either ways I think this shall be good to merge once sanity passes.

**Comment by erikh** [comment]
No, let's not; it's going to impact our system tests, and it appears to 
run ansible et al faster.

-Erik

**Comment by mapuri** [comment]
SGTM, merging this then!

**Pull request merged**
